require("general/mappings")
require("general/plugins")

require("plug-config/blankline")
require("plug-config/bufferline")
require("plug-config/codewindow")
require("plug-config/formatter")
require("plug-config/gitsigns")
require("plug-config/lualine")
require("plug-config/neoscroll")
require("plug-config/neo-tree")
-- require("plug-config/nvim-tree")
require("plug-config/nvim-ts-context-commentstring")
require("plug-config/scrollview")
require("plug-config/telescope")
require("plug-config/treesitter")
